### ISSUE TITLE
Bugs 190429

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_HoldTheLine.Tembelan#1]
- [x] Grenadier hat HE Unterlauf und keine Magazine
- [x] Grenadier Blufor hat keinen Unterlauf Rauch
- [x] Opfor Trucks haben keine Sitzbänke
- [x] Stamina war irgendwie immer noch mega schnell weg

**Comment by TheWillard** [comment]
- [x] Fahrzeug Inventar von manchen Fahrzeugen war nicht leer
